name: deployment workflow
on:
   push:
    branches: [master]

    jobs:
      job_one :
       name: deploy
       runs_on: egirna@egirna
       steps:
       name: testing egirna server ssh connection
       uses: appleboy/ssh-action@master
       with:
         host: egirna
         username: egirna
         key: ${{ EGIRNA_GITHUB_SECRET }}
         port: 22311
         
         
         
         
       
       
