name: ICAPeg Setup and Execution

on:
  push:
    branches:
      - master  # Trigger the pipeline on pushes to the main branch

jobs:
  build-and-run:
    runs-on:  self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.16'  # Install Go 1.16 or later

      - name: Configure proxy (if needed)
        run: |
          if [[ -z "$http_proxy" && -z "$https_proxy" ]]; then
            echo "Proxy server environment variables are not set. Configuring proxy..."
            export http_proxy="http://your_proxy_server:proxy_port"
            export https_proxy="http://your_proxy_server:proxy_port"
            echo "Proxy server configured. Please ensure your proxy server is running."
          fi
        env:
          your_proxy_server: ${{ secrets.PROXY_SERVER }}  # Store proxy details in GitHub secrets
          proxy_port: ${{ secrets.PROXY_PORT }}

      - name: Clone ICAPeg repository (if not present)
        run: |
          if [ ! -d "icapeg" ]; then
            git clone https://github.com/egirna/icapeg.git
          else
            echo "icapeg repository already exists. Skipping cloning."
          fi

      - name: Build ICAPeg
        run: go build .
        working-directory: icapeg

      - name: Run ICAPeg
        run: ./icapeg -port 1344  # Use default port or get it from input if needed
        working-directory: icapeg

    
