name: icapeg Setup and Run (Bash Script)

on:
  push:
    branches: master # Trigger on pushes to the main branch


jobs:
  build_and_run:
    runs-on:  egirna@egirna
      
    

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: testing egirna server ssh connection
        uses: appleboy/ssh-action@master
        with:
         host: egirna
         username: egirna
         key: ${{ EGIRNA_GITHUB_SECRET }}
         port: 22311
         
         

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21' # Or specify the Go version you need

      - name: Run setup script
        run: |
          chmod +x setup_icapeg.sh  # Make the script executable
          ./setup_icapeg.sh         # Execute the script

    
